# After any change to this file you MUST regenerate and checkin
# a .drone.sec even if no secrets were changed. The secrets file is tied
# to a specific .drone.yml so artifacts will not be uploaded to Bintray
# in following builds without an updated .drone.sec
---
clone:
  path: github.com/vmware/vic
  tags: true

build:
  vic:
    image: golang:1.6.3
    pull: true
    environment:
      BIN: bin
      GOPATH: /drone
      SHELL: /bin/bash
      DOCKER_API_VERSION: "1.21"
      VIC_ESX_TEST_URL: $$VIC_ESX_TEST_URL
      BUILD_NUMBER: $$BUILD_NUMBER
      COMMIT: $$COMMIT
    commands:
      - make mark
      - apt-get update
      - apt-get install -yq time
      - make -j9 all
      - make -j9 test
      - make sincemark

  integration-test-on-pr:
    image: $${TEST_BUILD_IMAGE=vmware-docker-ci-repo.bintray.io/integration/vic-test:1.4}
    pull: true
    environment:
      BIN: bin
      GOPATH: /drone
      SHELL: /bin/bash
      DOCKER_API_VERSION: "1.21"
      VIC_ESX_TEST_URL: $$VIC_ESX_TEST_URL
      LOG_TEMP_DIR: install-logs
      GITHUB_AUTOMATION_API_KEY:  $$GITHUB_AUTOMATION_API_KEY
      DRONE_SERVER:  $$DRONE_SERVER
      DRONE_TOKEN:  $$DRONE_TOKEN
      TEST_URL_ARRAY:  $$TEST_URL_ARRAY
      TEST_USERNAME:  $$TEST_USERNAME
      TEST_PASSWORD:  $$TEST_PASSWORD
      TEST_DATASTORE: $$TEST_DATASTORE
      TEST_TIMEOUT: $$TEST_TIMEOUT
      GOVC_INSECURE: true
      GOVC_USERNAME:  $$TEST_USERNAME
      GOVC_PASSWORD:  $$TEST_PASSWORD
      GOVC_RESOURCE_POOL:  $$TEST_RESOURCE
      GOVC_DATASTORE: $$TEST_DATASTORE
      GS_PROJECT_ID: $$GS_PROJECT_ID
      GS_CLIENT_EMAIL: $$GS_CLIENT_EMAIL
      GS_PRIVATE_KEY: $$GS_PRIVATE_KEY
    commands:
      - make mark
      - tests/integration-test.sh
      - make sincemark
    when:
      success: true
